restart.exclude.langchain4j=.*/langchain4j.*\.jar
restart.exclude.dev-langchain4j=dev/langchain4j/.*\.class
restart.exclude.dev-langchain4j-model=dev/langchain4j/model/.*\.class
restart.exclude.dev-langchain4j-service=dev/langchain4j/service/.*\.class
